# Generated by Django 5.0.2 on 2024-05-05 10:33

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=thumbnails.fields.ImageField(default=1, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
