# Generated by Django 5.0.6 on 2024-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_shoe_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='no_photos',
            field=models.BooleanField(default=False),
        ),
    ]
