# Generated by Django 5.0.2 on 2024-04-14 11:14

import tracker.core.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='measurement_unit',
            field=tracker.core.model_fields.ChoicesPositiveSmallIntegerField(default=1),
        ),
    ]
