name: Tests

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: shoe_wear_tracker
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Restore pip dependencies files
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install environment dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          cp tracker/local_settings.ci.py tracker/local_settings.py

      - name: Run tests
        run: python manage.py test
